chore: Polkadot v1.1.0 (#627)
# Fixes https://github.com/KILTprotocol/ticket/issues/2946 

Updates the Polkadot dependencies to version 1.1.0 from the mono
repository.

I could not use the [PSVM](https://github.com/paritytech/psvm) tool due
to encountering two issues:

1. Installing the newest version 0.2.2 results in an error:

```
error: failed to compile `psvm v0.2.2`, intermediate artifacts can be found at `/tmp/cargo-installtsUfAO`

Caused by:
  failed to select a version for `env_logger`.
      ... required by package `psvm v0.2.2`
  versions that meet the requirements `^0.11.3` are: 0.11.3

  the package `psvm` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
   It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
 ```
2. I was able to install version 0.1.0, but only versions from 1.3.0 to 1.8.0 are provided there.


An async backing configuration is implemented, preserving the current parachain behavior.


<details>
<summary>Peregrine Diff</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS
!!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
[≠] Version: [ 48, 109, 97, 115, 104, 110, 101, 116, 45, 110, 111, 100,
101, 48, 109, 97, 115, 104, 110, 101, 116, 45, 110, 111, 100, 101, 4, 0,
0, 0, 136, 44, ... ]
[Value([Changed(38, U8Change(60, 64)), Changed(159, U8Change(234, 215)),
Changed(160, U8Change(147, 189)), Changed(161, U8Change(227, 216)),
Changed(162, U8Change(241, 162)), Changed(163, U8Change(111, 114)),
Changed(164, U8Change(61, 202)), Changed(165, U8Change(105, 13)),
Changed(166, U8Change(98, 101)), Changed(167, U8Change(2, 1)),
Changed(171, U8Change(38, 234)), Changed(172, U8Change(96, 147)),
Changed(173, U8Change(149, 227)), Changed(174, U8Change(85, 241)),
Changed(175, U8Change(192, 111)), Changed(176, U8Change(101, 61)),
Changed(177, U8Change(102, 105)), Changed(178, U8Change(3, 98)),
Changed(183, U8Change(164, 38)), Changed(184, U8Change(123, 96)),
Changed(185, U8Change(125, 149)), Changed(186, U8Change(84, 85)),
Changed(187, U8Change(73, 192)), Changed(188, U8Change(148, 101)),
Changed(189, U8Change(201, 102)), Changed(190, U8Change(155, 3)),
Changed(191, U8Change(1, 2)), Changed(195, U8Change(69, 164)),
Changed(196, U8Change(191, 123)), Changed(197, U8Change(186, 125)),
Changed(198, U8Change(81, 84)), Changed(199, U8Change(163, 73)),
Changed(200, U8Change(16, 148)), Changed(201, U8Change(178, 201)),
Changed(202, U8Change(35, 155)), Changed(207, U8Change(195, 69)),
Changed(208, U8Change(179, 191)), Changed(209, U8Change(232, 186)),
Changed(210, U8Change(211, 81)), Changed(211, U8Change(50, 163)),
Changed(212, U8Change(115, 16)), Changed(213, U8Change(153, 178)),
Changed(214, U8Change(13, 35)), Changed(219, U8Change(8, 195)),
Changed(220, U8Change(0, 179)), Changed(221, U8Change(0, 232)),
Changed(222, U8Change(0, 211)), Changed(223, U8Change(0, 50)),
Added(224, 115), Added(225, 153), Added(226, 13), Added(227, 1),
Added(228, 0), Added(229, 0), Added(230, 0), Added(231, 8), Added(232,
0), Added(233, 0), Added(234, 0), Added(235, 0)])]

[≠] pallet 24: AuraExt -> 1 change(s)
  - storages changes:
[+] StorageDesc { name: "SlotInfo", modifier: "Optional", default_value:
[0] }

[≠] pallet 31: Council -> 1 change(s)
  - errors changes:
    [+] ErrorDesc { index: 10, name: "PrimeAccountNotMember" }

[≠] pallet 32: TechnicalCommittee -> 1 change(s)
  - errors changes:
    [+] ErrorDesc { index: 10, name: "PrimeAccountNotMember" }

[≠] pallet 80: ParachainSystem -> 3 change(s)
  - storages changes:
[+] StorageDesc { name: "AggregatedUnincludedSegment", modifier:
"Optional", default_value: [0] }
[+] StorageDesc { name: "UnincludedSegment", modifier: "Default",
default_value: [0] }
[+] StorageDesc { name: "UpgradeGoAhead", modifier: "Default",
default_value: [0] }

[-] pallet 9: Configuration
SUMMARY:
- Compatible.......................: false
- Require transaction_version bump.: false

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS
!!!
```

</details>

<details>
<summary>Spiritnet Diff</summary>

```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS
!!!
[≠] pallet 0: System -> 1 change(s)
  - constants changes:
[≠] Version: [ 56, 107, 105, 108, 116, 45, 115, 112, 105, 114, 105, 116,
110, 101, 116, 56, 107, 105, 108, 116, 45, 115, 112, 105, 114, 105, 116,
110, 101, 116, 1, 0, ... ]
[Value([Changed(42, U8Change(60, 64)), Changed(163, U8Change(234, 215)),
Changed(164, U8Change(147, 189)), Changed(165, U8Change(227, 216)),
Changed(166, U8Change(241, 162)), Changed(167, U8Change(111, 114)),
Changed(168, U8Change(61, 202)), Changed(169, U8Change(105, 13)),
Changed(170, U8Change(98, 101)), Changed(171, U8Change(2, 1)),
Changed(175, U8Change(38, 234)), Changed(176, U8Change(96, 147)),
Changed(177, U8Change(149, 227)), Changed(178, U8Change(85, 241)),
Changed(179, U8Change(192, 111)), Changed(180, U8Change(101, 61)),
Changed(181, U8Change(102, 105)), Changed(182, U8Change(3, 98)),
Changed(187, U8Change(164, 38)), Changed(188, U8Change(123, 96)),
Changed(189, U8Change(125, 149)), Changed(190, U8Change(84, 85)),
Changed(191, U8Change(73, 192)), Changed(192, U8Change(148, 101)),
Changed(193, U8Change(201, 102)), Changed(194, U8Change(155, 3)),
Changed(195, U8Change(1, 2)), Changed(199, U8Change(69, 164)),
Changed(200, U8Change(191, 123)), Changed(201, U8Change(186, 125)),
Changed(202, U8Change(81, 84)), Changed(203, U8Change(163, 73)),
Changed(204, U8Change(16, 148)), Changed(205, U8Change(178, 201)),
Changed(206, U8Change(35, 155)), Changed(211, U8Change(195, 69)),
Changed(212, U8Change(179, 191)), Changed(213, U8Change(232, 186)),
Changed(214, U8Change(211, 81)), Changed(215, U8Change(50, 163)),
Changed(216, U8Change(115, 16)), Changed(217, U8Change(153, 178)),
Changed(218, U8Change(13, 35)), Changed(223, U8Change(8, 195)),
Changed(224, U8Change(0, 179)), Changed(225, U8Change(0, 232)),
Changed(226, U8Change(0, 211)), Changed(227, U8Change(0, 50)),
Added(228, 115), Added(229, 153), Added(230, 13), Added(231, 1),
Added(232, 0), Added(233, 0), Added(234, 0), Added(235, 8), Added(236,
0), Added(237, 0), Added(238, 0), Added(239, 0)])]

[≠] pallet 24: AuraExt -> 1 change(s)
  - storages changes:
[+] StorageDesc { name: "SlotInfo", modifier: "Optional", default_value:
[0] }

[≠] pallet 31: Council -> 1 change(s)
  - errors changes:
    [+] ErrorDesc { index: 10, name: "PrimeAccountNotMember" }

[≠] pallet 32: TechnicalCommittee -> 1 change(s)
  - errors changes:
    [+] ErrorDesc { index: 10, name: "PrimeAccountNotMember" }

[≠] pallet 80: ParachainSystem -> 3 change(s)
  - storages changes:
[+] StorageDesc { name: "AggregatedUnincludedSegment", modifier:
"Optional", default_value: [0] }
[+] StorageDesc { name: "UnincludedSegment", modifier: "Default",
default_value: [0] }
[+] StorageDesc { name: "UpgradeGoAhead", modifier: "Default",
default_value: [0] }

SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: false

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS
!!!
```

</details>

## Checklist:

- [x] I have verified that the code works
  - [ ] No panics! (checked arithmetic ops, no indexing `array[3]` use `get(3)`, ...)
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)
    * Either PR or Ticket to update [the Docs](https://github.com/KILTprotocol/docs)
    * Link the PR/Ticket here

```

---------

Co-authored-by: Antonio <antonio@kilt.io>